spring:
  application:
    name: stock-service

server:
  port: 8181
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-3-16-161-166.us-east-2.compute.amazonaws.com:8761/eureka
    
      