spring:
  application:
    name: stock-service

server:
  port: 8181
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://financeplanning.herokuapp.com/eureka
    
      