package com.revature.api.domain;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.Map;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Pattern;

import com.google.gson.Gson;

/**
 * @author sweinhart
 *
 */
@Entity
@Table(name = "expenses")
public class Expense implements Comparable<Expense> {

	/**
	 * Expense id - AutoGenerated on save
	 */
	@Id
	@GeneratedValue(generator = "clients_id_seq", strategy = GenerationType.IDENTITY)
	private Integer id;

	/**
	 * Organization Name
	 */
	@Pattern(regexp = "[a-zA-Z\\s]+")
	@javax.validation.constraints.Size(min = 2, max = 20)
	@NotBlank
	private String organization;

	/**
	 * Expense Description
	 */
	@Pattern(regexp = "[a-zA-Z\\s]+")
	@javax.validation.constraints.Size(min = 2, max = 20)
	@NotBlank
	private String description;

	/**
	 * Expense Amount in US Dollars
	 */
	private String amount;
	
	/**
	 * Date in yyyy-MM-dd format
	 */
	private String date;
	
	/**
	 * Quantity if items purchased
	 */
	private Integer quantity;

	/**
	 * Empty Constructor
	 */
	public Expense() {
		super();
	}

	/**
	 * Get Expense id
	 * 
	 * @return id : Integer
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * Set Expense id
	 * 
	 * @param id : Integer
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get Organization Name
	 * 
	 * @return organization : String
	 */
	public String getOrganization() {
		return organization;
	} 

	/**
	 * Set Organization Name
	 * 
	 * @param organization : String
	 */
	public void setOrganization(String organization) {
		this.organization = organization;
	}

	/**
	 * Get Expense Amount
	 * 
	 * @return amount : String
	 */
	public String getAmount() {
		return amount;
	}

	/**
	 * Set Expense Amount
	 * 
	 * @param amount : String
	 */
	public void setAmount(String amount) {
		this.amount = amount;
	}

	/**
	 * Get Expense Description
	 * 
	 * @return description : String
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Set Expense Description
	 * 
	 * @param description : String
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get Expense Date
	 * 
	 * @return date : String yyyy-MM-dd
	 */
	public String getDate() {
		return date;
	}

	/**
	 * Set Expense Date
	 * 
	 * @param date : String yyyy-MM-dd
	 */
	public void setDate(String date) {
		this.date = date;
	}

	/**
	 * Get Expense Item Quantity
	 * 
	 * @return quantity : Integer
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * Set Expense Item Quantity
	 * 
	 * @param quantity : Integer
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Override
	public String toString() {
		Gson gson = new Gson();
		return gson.toJson(this);
	}

	@Override
	public int compareTo(Expense o) {
		return date.compareTo(o.date);
	}

	public static Expense from(Map<String, Object> payload) throws RuntimeException {
		Expense expense = new Expense();
		expense.setOrganization((String) payload.get("organization"));
		Object amount = payload.get("amount");
		String amountClass = amount.getClass().getName();
		switch (amountClass) {
		case ("java.lang.Integer"): {
			expense.setAmount(BigDecimal.valueOf((Integer)amount));
			break;
		}
		case ("java.lang.Double"): {
			expense.setAmount(BigDecimal.valueOf((Double)amount));
			break;
		}
		case ("java.lang.String"): {
			expense.setAmount(BigDecimal.valueOf(Double.parseDouble((String) amount)));
			break;
		}
		}
		expense.setDate(Date.valueOf((String) payload.get("date")));
		expense.setDescription((String) payload.get("description"));
		expense.setQuantity((Integer) payload.get("quantity"));
		return expense;
	}

}
