#%RAML 1.0
title: Expense
/expense:
  post:
    description: Add an expense
    body:
      application/json:
        example: |
          {
            "name": "Fire Department",
            "amount": 800.00,
            "date": "2019-04-01"
          }
    responses:
      201:
  /{organization}:
    get:
      queryParameters:
        start:
          displayName: Start Date
          type: date-only
          description: Only show expenses later than this date.
          example: 2006-01-01
        end:
          displayName: End Date
          type: date-only
          description: Only show expenses earlier than this date.
          example: 2019-04-01
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "name": "Fire Department",
                    "amount": 45.00,
                    "date": "2019-04-01T00:00:00.000+0000"
                  },
                  {
                    "name": "Fire Department",
                    "amount": 35.00,
                    "date": "2019-01-01T00:00:00.000+0000"
                  },
                  {
                    "name": "Fire Department",
                    "amount": 40.00,
                    "date": "2018-10-01T00:00:00.000+0000"
                  },
                  {
                    "name": "Fire Department",
                    "amount": 85.00,
                    "date": "2018-07-01T00:00:00.000+0000"
                  }
                ]
    /{date}:
      get:
        responses:
          200:
            body:
              application/json:
                example: |
                    {
                      "name": "Fire Department",
                      "amount": 85.00,
                      "date": "2018-07-01T00:00:00.000+0000"
                    }
      put:
        description: overwrite an expense
        body:
          application/json:
            example: |
              {
                "name": "Fire Department",
                "amount": 799.00,
                "date": "2019-04-01"
              }
        responses:
          200:     
      delete:
        description: delete an expense
        responses:
          204:
