#%RAML 1.0
title: Total
version: v1

types:
  Group: 
    type: object
    properties: 
      organization: string
      amount: number
/total:
  /expenses:
    /{organization}/{date1}/{date2}:
      get:
        description: get expenses summarized over the quarter, which is date1 and date2
        responses:
          200:
            body:
              application/json:
                example: |
                  [
                    {
                      "organization": "Fire Department",
                      "amount": "10.00"
                    }
                  ]
          404:
            body: 
              application/json:
                example: |
                  {"message": "no fieldtrip locations available"}
    /all/{organization}:
      get:
        description: get expenses over all inputs
        responses:
          200:
            body:
              application/json:
                example: |
                  [
                    {
                      "organization": "Fire Department",
                      "amount": "10.00"
                    }
                  ]
          404:
            body: 
              application/json:
                example: |
                  {"message": "no fieldtrip locations available"}
    /after/{organization}/{date}:
      get:
        description: get expenses over all inputs
        responses:
          200:
            body:
              application/json:
                example: |
                  [
                    {
                      "organization": "Fire Department",
                      "amount": "10.00"
                    }
                  ]
          404:
            body: 
              application/json:
                example: |
                  {"message": "no fieldtrip locations available"}
  /revenues:
    /{organization}/{date1}/{date2}:
      get:
        description: get revenues summarized over the quarter, which is date1 and date2
        responses:
          200:
            body:
              application/json:
                example: |
                  [
                    {
                      "organization": "fire",
                      "amount": "10.00"
                    }
                  ]
           404:
            body: 
              application/json:
                example: |
                  {"message": "no fieldtrip locations available"}
    /all/{organization}:
      get:
        description: get revenues over all inputs
        responses:
          200:
            body:
              application/json:
                example: |
                  [
                    {
                      "organization": "fire",
                      "amount": "10.00"
                    }
                  ]
           404:
            body: 
              application/json:
                example: |
                  {"message": "no fieldtrip locations available"}
    /after/{organization}/{date}:
      get:
        description: get expenses over all inputs
        responses:
          200:
            body:
              application/json:
                example: |
                  [
                    {
                      "organization": "fire",
                      "amount": "10.00"
                    }
                  ]
          404:
            body: 
              application/json:
                example: |
                  {"message": "no fieldtrip locations available"}
